# Generated by Django 5.2 on 2025-04-15 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0007_transaction_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='isReconciled',
            new_name='is_reconciled',
        ),
    ]
