# Generated by Django 5.2 on 2025-04-22 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0009_alter_transaction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
    ]
