# Generated by Django 5.2 on 2025-05-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0013_vendor_delete_vendors'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
