# Generated by Django 5.2 on 2025-05-07 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0015_entity_delete_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='payee',
        ),
        migrations.AddField(
            model_name='transaction',
            name='entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core_backend.entity'),
        ),
    ]
