# Generated by Django 5.2 on 2025-05-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0016_remove_transaction_payee_transaction_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('journal', 'Journal'), ('account', 'Account')], default='account', max_length=10),
        ),
    ]
