# Generated by Django 5.2 on 2025-05-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0019_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='phone_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
