# Generated by Django 5.2 on 2025-05-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0020_entity_email_entity_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
