# Generated by Django 5.2 on 2025-06-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0022_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='notes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('multi_unit', 'Multi-Unit')], default='residential', max_length=25),
        ),
    ]
