# Generated by Django 5.2 on 2025-06-11 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0023_alter_property_notes_alter_property_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='core_backend.property'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core_backend.property'),
        ),
    ]
