# Generated by Django 5.2 on 2025-06-16 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0024_entity_property_transaction_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='core_backend.property'),
        ),
    ]
