# Generated by Django 5.2 on 2025-06-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0026_property_current_rent_due_rentpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentpayment',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
