# Generated by Django 5.2 on 2025-08-04 17:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0029_alter_transaction_type_journalitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journalitem',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journalitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
