# Generated by Django 5.2 on 2025-08-04 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0030_journalitem_created_at_journalitem_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalitem',
            name='property',
        ),
        migrations.AddField(
            model_name='journalitem',
            name='journal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_items', to='core_backend.journal'),
        ),
    ]
