# Generated by Django 5.2 on 2025-08-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0031_remove_journalitem_property_journalitem_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='normal_balance',
            field=models.CharField(blank=True, choices=[('debit', 'Debit'), ('credit', 'Credit'), ('na', 'Na')], default='asset', max_length=10, null=True),
        ),
    ]
