# Generated by Django 5.2 on 2025-08-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0032_account_normal_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='normal_balance',
            field=models.CharField(blank=True, choices=[('debit', 'Debit'), ('credit', 'Credit'), ('na', 'Na')], default='na', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(blank=True, choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('expense', 'Expense'), ('bank', 'Bank'), ('credit-card', 'Credit-Card')], default='asset', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('multi-unit', 'Multi-Unit')], default='residential', max_length=25),
        ),
    ]
