# Generated by Django 5.2 on 2025-09-29 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0033_alter_account_normal_balance_alter_account_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='normal_balance',
        ),
    ]
