# Generated by Django 5.2 on 2025-10-14 12:27

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0034_remove_account_normal_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
