# Generated by Django 5.2 on 2025-12-08 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0035_alter_entity_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('na', 'NA'), ('balance_sheet', 'Balance Sheet'), ('profit_loss', 'Profit & Loss')], default='na', max_length=25, null=True)),
                ('report_range_type', models.CharField(blank=True, choices=[('last_year', 'Last Year'), ('year_to_date', 'Year to Date'), ('all_time', 'All Time'), ('custom', 'Custom')], default='custom', max_length=25, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('report_ran_on_date', models.DateField(null=True)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core_backend.property')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
