# Generated by Django 5.2 on 2025-12-08 18:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0036_reporthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporthistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporthistory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
