# Generated by Django 5.2 on 2025-12-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0037_reporthistory_created_at_reporthistory_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporthistory',
            name='report_ran_on_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
